#
# Copyright (c) 2010 rPath, Inc.
#
# All rights reserved.
#

static_files = \
	__init__.py		\
	rusconf.py		\


all: default-all

install: default-install

clean: default-clean


include $(TOP)/Make.rules
# vim: set sts=8 sw=8 noexpandtab :
