#
# Copyright (c) 2008 rPath, Inc.
#
# All Rights Reserved
#

SUBDIRS = srv web

kid_files = reaentitlement.kid

static_files = __init__.py


all: default-all

install: default-install

clean: default-clean


include $(TOP)/Make.rules
# vim: set sts=8 sw=8 noexpandtab :
