#
# Copyright (c) SAS Institute Inc.
#

override DEST = $(PYDIR)/$(DIR)

static_files = $(wildcard *.py)

all: default-all

install: default-install

clean: default-clean


include $(TOP)/Make.rules
# vim: set sts=8 sw=8 noexpandtab :
