#!/usr/bin/python
#
# Copyright 2006-2007 rPath, Inc.
# All Rights Reserved
#
import sys
import os
import urllib

from reposconary.conary.repository.netrepos.netserver import ServerConfig

CONARYRC = '/srv/www/html/conaryrc'
CNR = '/srv/conary/repository.cnr'

# Nothing to do if repository.cnr or conaryrc do not exist
if not os.path.exists(CONARYRC) or not os.path.exists(CNR):
    sys.exit(0)

# Check the value of forceSSL and use the appropriate protocol
cfg = ServerConfig()
cfg.read(CNR)
if cfg.forceSSL:
    protocol = 'https'
else:
    protocol = 'http'

# Iterate though the repo maps and update them as necessary
cfg.read(CONARYRC)
updatedMaps = {}
for k,v in cfg.repositoryMap.items():
    repo = urllib.splittype(v)[1]
    updatedMaps.update({k : '%s:%s' % (protocol, repo)})

# Write out the new conaryrc
fd = open(CONARYRC, 'w')
cfg.repositoryMap = updatedMaps
cfg.displayKey('repositoryMap', out = fd)
fd.close()
