#!/bin/bash

logfile=/var/log/rbuilder/migration.log
(
echo Beginning migration to Conary $(conary --version)
echo Date: $(date)
python -mupsrv.conary_schema; rc=$?
echo Exit code: $rc
echo
) 2>&1 |tee -a $logfile

exit 0
