#
# Copyright (c) 2010 rPath, Inc.
#
# All rights reserved.
#

all: default-all

install: default-install
	install -D -m0644 corplogo.png $(DESTDIR)/usr/share/conary/web-common/images/corplogo.png
	install -D -m0644 prodlogo.gif $(DESTDIR)/usr/share/conary/web-common/images/prodlogo.gif
	install -D -m0644 custom.css $(DESTDIR)/usr/share/conary/web-common/css/custom.css

clean: default-clean


include $(TOP)/Make.rules
# vim: set sts=8 sw=8 noexpandtab :
