#
# Copyright (c) 2008 rPath, Inc.
#
# All Rights Reserved
#

SUBDIRS = rpc web

plugin_config_files = conaryserver.cfg

static_files = __init__.py


all: default-all

install: default-install

clean: default-clean


include $(TOP)/Make.rules
# vim: set sts=8 sw=8 noexpandtab :
